# Assignment-5 — UCS420 Cognitive Computing
**Name:** Manroop Kaur


## Q1. NumPy 1-D array and basic operations

In [1]:
import numpy as np

# Create a 1-D NumPy array with 5 elements
arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)
print("Add 2 to every element:", arr + 2)
print("Multiply every element by 3:", arr * 3)
print("Divide every element by 2:", arr / 2)

Original array: [10 20 30 40 50]
Add 2 to every element: [12 22 32 42 52]
Multiply every element by 3: [ 30  60  90 120 150]
Divide every element by 2: [ 5. 10. 15. 20. 25.]


## Q2. Basic NumPy array operations

### Q2(a). Reverse the NumPy array

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


### Q2(b). Find the most frequent value and its index/indices

In [3]:
def most_frequent_values_and_indices(array):
    values, counts = np.unique(array, return_counts=True)
    max_count = counts.max()
    most_frequent = values[counts == max_count]

    print("Array:", array)
    print("Most frequent value(s):", most_frequent)
    print("Frequency:", max_count)

    for value in most_frequent:
        indices = np.where(array == value)[0]
        print(f"Indices of {value}:", indices)


# i
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent_values_and_indices(x)

print()

# ii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_values_and_indices(y)

Array: [1 2 3 4 5 1 2 1 1 1]
Most frequent value(s): [1]
Frequency: 5
Indices of 1: [0 5 7 8 9]

Array: [1 1 1 2 3 4 2 4 3 3]
Most frequent value(s): [1 3]
Frequency: 3
Indices of 1: [0 1 2]
Indices of 3: [4 8 9]


## Q3. Access elements of a 2-D array using row and column indices

In [4]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2-D array:\n", arr)

# a) 1st row, 2nd column
# NumPy uses 0-based indexing, so this is arr[0, 1]
print("1st row, 2nd column:", arr[0, 1])

# b) 3rd row, 1st column
# This is arr[2, 0]
print("3rd row, 1st column:", arr[2, 0])

2-D array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


## Q4. Create a 1-D array with 25 evenly spaced numbers from 10 to 100

In [5]:
ucs420_Manroop = np.linspace(10, 100, 25)

print("Array:\n", ucs420_Manroop)
print("Dimensions (ndim):", ucs420_Manroop.ndim)
print("Shape:", ucs420_Manroop.shape)
print("Total elements (size):", ucs420_Manroop.size)
print("Data type:", ucs420_Manroop.dtype)
print("Total bytes consumed (nbytes):", ucs420_Manroop.nbytes)

Array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type: float64
Total bytes consumed (nbytes): 200


### Transpose using reshape()
A 1-D array does not change shape when `.T` is applied. To demonstrate a meaningful transpose, first reshape the 25 elements into a 5×5 matrix and then transpose it.

In [7]:
reshaped_ucs420_Manroop = ucs420_Manroop.reshape(5, 5)
transpose_ucs420_Manroop = reshaped_ucs420_Manroop.T

print("5 x 5 array using reshape():\n", reshaped_ucs420_Manroop)
print("Transpose of the 5 x 5 array using .T:\n", transpose_ucs420_Manroop)

# Can .T be used directly on the original 1-D array?
print("Shape of original 1-D array:", ucs420_Manroop.shape)
print("Shape after applying .T directly:", ucs420_Manroop.T.shape)
print("Therefore, .T does not change a 1-D array's shape.")

5 x 5 array using reshape():
 [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
Transpose of the 5 x 5 array using .T:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
Shape of original 1-D array: (25,)
Shape after applying .T directly: (25,)
Therefore, .T does not change a 1-D array's shape.


## Q5. 2-D array operations

In [8]:
ucs420_Saisha = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original 2-D array:\n", ucs420_Manroop)
print("\nMean:", np.mean(ucs420_Manroop))
print("Median:", np.median(ucs420_Manroop))
print("Maximum:", np.max(ucs420_Manroop))
print("Minimum:", np.min(ucs420_Manroop))
print("Unique elements:", np.unique(ucs420_Manroop))

Original 2-D array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Mean: 55.0
Median: 55.0
Maximum: 100.0
Minimum: 10.0
Unique elements: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


### Reshape to 4 rows × 3 columns

In [10]:
reshaped_ucs420_Manroop = ucs420_Manroop.reshape(4, 3)

print("reshaped_ucs420_Manroop:\n", reshaped_ucs420_Manroop)

ValueError: cannot reshape array of size 25 into shape (4,3)

### Resize to 2 rows × 3 columns

In [11]:
resized_ucs420_Manroop = np.resize(ucs420_Manroop, (2, 3))

print("resized_ucs420_Manroop:\n", resized_ucs420_Manroop)

resized_ucs420_Manroop:
 [[10.   13.75 17.5 ]
 [21.25 25.   28.75]]
